import { escapeHtml, formatDate } from "../utils/html.js";
import { progressOf, requiredChecksComplete } from "../domain/workflowEngine.js";
import { workflowMap } from "./workflowMap.js";
import { taskForm } from "./workflowEditor.js";

const labels={blocked:"진입 대기",ready:"수행 가능",in_progress:"진행 중",completed:"완료"};

export function renderRuns(state,ui){
 const run=state.instances.find(item=>item.id===state.selectedInstanceId)||state.instances[0];
 if(!run)return `<section class="page"><div class="empty tall"><span>▶</span><strong>실행 건이 없습니다</strong><p>Workflow 설계 화면에서 실행을 시작해 주세요.</p><button class="primary" data-action="navigate" data-view="workflows">설계로 이동</button></div></section>`;
 const workflow=run.definitionSnapshot;
 const definition=workflow.tasks.find(task=>task.id===ui.selectedTaskId)||workflow.tasks.find(task=>run.tasks.find(item=>item.taskId===task.id&&["ready","in_progress"].includes(item.status)))||workflow.tasks[0];
 const runtimeTask=run.tasks.find(task=>task.taskId===definition.id),progress=progressOf(run);
 const resetDefinition=workflow.tasks.find(task=>task.id===ui.resetTaskId);
 const editing=ui.runEditMode?workflow.tasks.find(task=>task.id===ui.editingTaskId):null;
 const mapInstance=ui.runEditMode?null:run;
 return `<section class="page"><div class="toolbar"><label>실행 건<select data-action="select-run">${state.instances.map(item=>`<option value="${item.id}" ${item.id===run.id?"selected":""}>${escapeHtml(item.name)}</option>`).join("")}</select></label><div class="toolbar-actions"><button class="secondary" data-action="download-run-report">▤ 리포트</button><button class="secondary" data-action="open-template-dialog">☆ 템플릿 저장</button><button class="${ui.runEditMode?"primary":"secondary"}" data-action="toggle-run-edit">${ui.runEditMode?"✓ 실행 편집 완료":"✎ 실행 Workflow 편집"}</button><div class="run-summary"><span>전체 진행률</span><strong>${progress}%</strong><div class="progress"><i style="width:${progress}%"></i></div></div></div></div>${ui.runEditMode?`<div class="run-edit-banner"><strong>현재 실행 건 편집 중</strong><span>Task 추가·삭제·수정과 연결 관계 변경은 이 실행 건에만 적용됩니다. 기존 완료·체크 상태는 유지됩니다.</span></div>`:""}<div class="workspace ${ui.runEditMode?"canvas-workspace":""}"><div class="canvas-panel"><div class="canvas-head"><div><span class="eyebrow">${escapeHtml(workflow.name)} · V${run.workflowVersion}</span><h2>${escapeHtml(run.name)}</h2><p>${formatDate(run.createdAt)} 시작</p>${ui.runEditMode?`<small class="drag-hint">Task 이동, 화살표 연결 편집, 더블클릭 설정이 가능합니다.</small>`:""}</div><span class="status-pill ${ui.runEditMode?"ready":run.status==="completed"?"completed":"in_progress"}">${ui.runEditMode?"편집 중":run.status==="completed"?"완료":"실행 중"}</span></div>${workflowMap(workflow,mapInstance,definition.id,ui.expandedTaskIds,ui.mapZoom,ui.runEditMode?ui.selectedConnection:null)}${ui.runEditMode?`<button class="add-task" data-action="add-task" data-scope="run">＋ 실행 Task 추가</button>`:`<div class="history"><span class="eyebrow">ACTIVITY</span><h3>최근 활동</h3>${run.history.slice(0,7).map(item=>`<div><i></i><p>${escapeHtml(item.message)}<small>${formatDate(item.at)}</small></p></div>`).join("")}</div>`}</div><aside class="detail-panel ${ui.runEditMode?"workflow-side":""}">${runtime(definition,runtimeTask,run,ui.runEditMode)}</aside></div>${resetDefinition?resetDialog(resetDefinition,workflow):""}${editing?`<div class="modal-backdrop" data-action="close-task-settings"><section class="task-modal" role="dialog" aria-modal="true" aria-label="실행 Task 설정" data-action="modal-panel">${taskForm(editing,workflow,true,"run")}</section></div>`:""}${ui.templateRunId===run.id?templateDialog(run):""}</section>`;
}

function templateDialog(run){return `<div class="modal-backdrop" data-action="close-template-dialog"><section class="task-modal template-modal" role="dialog" aria-modal="true" aria-label="Workflow 템플릿 저장" data-action="modal-panel"><div class="panel-title"><div><span class="eyebrow">BEST PRACTICE TEMPLATE</span><h3>실행본을 Workflow로 저장</h3></div><button class="icon-button" data-action="close-template-dialog" type="button">×</button></div><p class="run-edit-notice">현재 실행에서 보완한 Task, 연결, ETVX와 체크리스트 구조를 새 Workflow 정의로 복제합니다. 실행 상태와 체크 결과는 포함하지 않습니다.</p><form data-form="save-run-template"><label>템플릿 이름<input name="name" value="${escapeHtml(run.definitionSnapshot.name)} · 모범 사례" required></label><label>설명<textarea name="description">${escapeHtml(run.definitionSnapshot.description||"")}</textarea></label><div class="reset-actions"><button type="button" class="secondary" data-action="close-template-dialog">취소</button><button class="primary" type="submit">Workflow 설계에 저장</button></div></form></section></div>`}

function runtime(task,runtimeTask,run,editing=false){
 const allowed=requiredChecksComplete(run,task.id),disabled=["blocked","completed"].includes(runtimeTask.status);
 const hasProgress=runtimeTask.startedAt||runtimeTask.completedAt||runtimeTask.checklist.some(item=>item.checked)||runtimeTask.subtasks.some(item=>item.completed);
 return `<div class="panel-title"><div><span class="status-pill ${runtimeTask.status}">${labels[runtimeTask.status]}</span><h3>${escapeHtml(task.title)}</h3><p class="owner">담당 · ${escapeHtml(task.assignee)} · 우선순위 ${task.priority}</p></div></div>${editing?`<button class="primary full run-task-edit" data-action="open-task-settings" data-task-id="${task.id}">이 실행 건의 Task 설정</button>`:""}${criteria("E","진입 기준",task.entry)}${criteria("T","수행 내용",task.instructions||"등록된 수행 지침이 없습니다.")}${task.subtasks.length?`<div class="runtime-checks subtasks"><div class="criteria-head"><b>S</b><div><span>Subtask</span><small>${runtimeTask.subtasks.filter(item=>item.completed).length}/${runtimeTask.subtasks.length} 완료</small></div></div>${task.subtasks.map(item=>{const done=runtimeTask.subtasks.find(value=>value.itemId===item.id)?.completed;return `<label class="runtime-check ${disabled?"disabled":""}"><input type="checkbox" data-action="toggle-subtask" data-task-id="${task.id}" data-item-id="${item.id}" ${done?"checked":""} ${disabled?"disabled":""}><span>${escapeHtml(item.title)}</span>${item.required?"<em>필수</em>":""}</label>`;}).join("")}</div>`:""}<div class="runtime-checks"><div class="criteria-head"><b>V</b><div><span>완료 체크리스트</span><small>${runtimeTask.checklist.filter(item=>item.checked).length}/${runtimeTask.checklist.length} 완료</small></div></div>${task.checklist.map(item=>{const checked=runtimeTask.checklist.find(value=>value.itemId===item.id)?.checked;return `<label class="runtime-check ${disabled?"disabled":""}"><input type="checkbox" data-action="toggle-check" data-task-id="${task.id}" data-item-id="${item.id}" ${checked?"checked":""} ${disabled?"disabled":""}><span>${escapeHtml(item.text)}</span>${item.required?"<em>필수</em>":""}</label>`;}).join("")}</div>${criteria("X","완료 기준",task.exit)}${editing?"":runtimeTask.status==="ready"?`<button class="primary full" data-action="start-task" data-task-id="${task.id}">업무 시작</button>`:""}${editing?"":runtimeTask.status==="in_progress"?`<button class="primary full" data-action="complete-task" data-task-id="${task.id}" ${allowed?"":"disabled"}>${allowed?"Task 완료":"필수 Subtask와 체크리스트를 완료해 주세요"}</button>`:""}${editing?"":runtimeTask.status==="blocked"?`<div class="blocked-note">선행 Task가 모두 완료되면 자동으로 열립니다.</div>`:""}${editing?"":runtimeTask.status==="completed"?`<div class="completed-note">✓ ${formatDate(runtimeTask.completedAt)} 완료</div>`:""}${editing?"":hasProgress?`<button class="reset-button full" data-action="open-reset-dialog" data-task-id="${task.id}">↺ Task 재수행 · Reset</button>`:""}`;
}

function resetDialog(task,workflow){
 const downstream=connectedCount(task.id,workflow)-1;
 return `<div class="modal-backdrop" data-action="close-reset-dialog"><section class="reset-modal" role="dialog" aria-modal="true" aria-label="Task Reset 확인" data-action="modal-panel"><div class="reset-icon">↺</div><span class="eyebrow">RESET TASK</span><h2>“${escapeHtml(task.title)}”을 다시 수행할까요?</h2><p class="reset-warning">Reset하면 체크리스트, Subtask, 시작·완료 시간이 초기화됩니다. 이 작업은 실행 이력에 기록됩니다.</p><form data-form="reset-task" data-task-id="${task.id}"><label class="reset-option"><input type="radio" name="resetScope" value="task" ${downstream?"":"checked"}><span><strong>현재 Task만 Reset</strong><small>후속 Task의 현재 상태와 완료 기록은 유지합니다.</small></span></label><label class="reset-option recommended"><input type="radio" name="resetScope" value="downstream" ${downstream?"checked":""}><span><strong>연결된 이후 모든 Task Reset</strong><small>현재 Task와 연결된 후속 Task ${downstream}개를 함께 초기화합니다.</small></span><em>권장</em></label><div class="reset-actions"><button type="button" class="secondary" data-action="close-reset-dialog">취소</button><button type="submit" class="reset-confirm">확인하고 Reset</button></div></form></section></div>`;
}

function connectedCount(taskId,workflow){const ids=new Set([taskId]);let changed=true;while(changed){changed=false;workflow.tasks.forEach(task=>{if(!ids.has(task.id)&&task.dependencies.some(id=>ids.has(id))){ids.add(task.id);changed=true;}});}return ids.size;}
const criteria=(letter,title,text)=>`<div class="criteria"><b>${letter}</b><div><span>${title}</span><p>${escapeHtml(text)}</p></div></div>`;
