import { escapeHtml } from "../utils/html.js";
import { workflowMap } from "./workflowMap.js";

export function renderWorkflowEditor(state,ui){
 const wf=state.workflows.find(w=>w.id===state.selectedWorkflowId)||state.workflows[0];
 if(!wf)return `<section class="page"><div class="empty"><strong>Workflow가 없습니다</strong><button class="primary" data-action="new-workflow">새 Workflow</button></div></section>`;
 const task=wf.tasks.find(t=>t.id===ui.selectedTaskId)||wf.tasks[0];
 const editing=wf.tasks.find(t=>t.id===ui.editingTaskId);
 return `<section class="page"><div class="toolbar"><label>Workflow<select data-action="select-workflow">${state.workflows.map(w=>`<option value="${w.id}" ${w.id===wf.id?"selected":""}>${escapeHtml(w.name)}</option>`).join("")}</select></label><div class="toolbar-actions"><button class="secondary" data-action="import-workflow">⇩ Import</button><input class="visually-hidden" type="file" data-workflow-import accept="application/json,.json"><button class="secondary" data-action="export-workflow" data-workflow-id="${wf.id}">⇧ Export</button><button class="secondary" data-action="new-workflow">+ 새 Workflow</button><button class="primary" data-action="start-run" data-workflow-id="${wf.id}">▶ 실행 시작</button></div></div><div class="workspace canvas-workspace"><div class="canvas-panel"><div class="canvas-head"><div><span class="eyebrow">VERSION ${wf.version}</span><h2>${escapeHtml(wf.name)}</h2><p>${escapeHtml(wf.description||"설명을 입력해 주세요.")}</p><small class="drag-hint">Task를 자유롭게 드래그하세요. 화살표를 클릭하면 양 끝점을 바꿀 수 있고, Task 더블클릭 시 설정이 열립니다.</small></div><button class="icon-button danger" data-action="delete-workflow" data-workflow-id="${wf.id}">×</button></div>${workflowMap(wf,null,task&&task.id,ui.expandedTaskIds,ui.mapZoom,ui.selectedConnection)}<button class="add-task" data-action="add-task" data-workflow-id="${wf.id}">＋ Task 추가</button></div><aside class="detail-panel workflow-side">${workflowForm(wf)}${task?`<div class="selected-task-summary"><span class="eyebrow">SELECTED TASK</span><strong>${escapeHtml(task.title)}</strong><p>${escapeHtml(task.assignee)} · ${escapeHtml(task.priority)}</p><button class="secondary full" data-action="open-task-settings" data-task-id="${task.id}">Task 설정 열기</button></div>`:""}</aside></div>${editing?`<div class="modal-backdrop" data-action="close-task-settings"><section class="task-modal" role="dialog" aria-modal="true" aria-label="Task 설정" data-action="modal-panel">${taskForm(editing,wf,true)}</section></div>`:""}</section>`;
}

function workflowForm(w){return `<div class="panel-title"><span class="eyebrow">WORKFLOW INFO</span><h3>기본 정보</h3></div><form data-form="workflow" data-workflow-id="${w.id}"><label>이름<input name="name" value="${escapeHtml(w.name)}" required></label><label>설명<textarea name="description">${escapeHtml(w.description)}</textarea></label><label>Owner<input name="owner" value="${escapeHtml(w.owner)}"></label><button class="primary full">저장</button></form>`;}
function itemsEditor(items,t,kind,scope){const sub=kind==="subtask";return `<div class="check-editor">${items.map(i=>`<div><input name="${sub?"subtask_text":"check_text"}_${i.id}" value="${escapeHtml(sub?i.title:i.text)}"><label class="mini-check"><input type="checkbox" name="${sub?"subtask_required":"check_required"}_${i.id}" ${i.required?"checked":""}>필수</label><button type="button" data-action="delete-${kind}" data-scope="${scope}" data-task-id="${t.id}" data-item-id="${i.id}">×</button></div>`).join("")}<button type="button" class="text-button" data-action="add-${kind}" data-scope="${scope}" data-task-id="${t.id}">+ ${sub?"Subtask":"체크 항목"}</button></div>`;}

export function taskForm(t,wf,modal=false,scope="definition"){const others=wf.tasks.filter(x=>x.id!==t.id),run=scope==="run";return `<div class="panel-title"><div><span class="eyebrow">${run?"RUN WORKFLOW":"ETVX TASK"}</span><h3>${escapeHtml(t.title)}</h3></div><div class="panel-actions">${modal?`<button class="icon-button" data-action="close-task-settings" type="button">×</button>`:""}<button class="icon-button danger" data-action="delete-task" data-scope="${scope}" data-task-id="${t.id}" type="button">⌫</button></div></div>${run?`<p class="run-edit-notice">이 변경은 현재 실행 건에만 반영되며 원본 Workflow 정의는 유지됩니다.</p>`:""}<form data-form="task" data-scope="${scope}" data-task-id="${t.id}"><label>Task 이름<input name="title" value="${escapeHtml(t.title)}" required></label><div class="field-row"><label>담당자 / 역할<input name="assignee" value="${escapeHtml(t.assignee)}"></label><label>우선순위<select name="priority"><option value="low" ${t.priority==="low"?"selected":""}>낮음</option><option value="medium" ${t.priority==="medium"?"selected":""}>보통</option><option value="high" ${t.priority==="high"?"selected":""}>높음</option><option value="critical" ${t.priority==="critical"?"selected":""}>긴급</option></select></label></div><fieldset class="dependency-editor"><legend>선행 Task · 모두 완료되면 실행</legend>${others.length?others.map(x=>`<label><input type="checkbox" name="dependencies" value="${x.id}" ${t.dependencies.includes(x.id)?"checked":""}>${escapeHtml(x.title)}</label>`).join(""):`<small>연결할 다른 Task가 없습니다.</small>`}<p>선택하지 않으면 다른 시작 Task와 병렬 실행됩니다.</p></fieldset><label class="etvx"><b>E</b><span>Entry · 진입 기준</span><textarea name="entry">${escapeHtml(t.entry)}</textarea></label><label class="etvx"><b>T</b><span>Task · 수행 내용</span><textarea name="instructions">${escapeHtml(t.instructions)}</textarea></label><div class="etvx subtask-section"><b>S</b><span>Subtask · 세부 수행 업무</span>${itemsEditor(t.subtasks,t,"subtask",scope)}</div><div class="etvx"><b>V</b><span>Validation · 체크리스트</span>${itemsEditor(t.checklist,t,"check",scope)}</div><label class="etvx"><b>X</b><span>Exit · 완료 기준</span><textarea name="exit">${escapeHtml(t.exit)}</textarea></label><button class="primary full">${run?"현재 실행 건에 반영":"변경사항 저장"}</button></form>`;}
